### ISSUE TITLE
Problema na organização da impressao  

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#11]
galera na hora de visualizar esta ótimo mais depois que imprime passa para outra pagina pois fica tudo disorganizado

**Comment by TecSecret** [comment]
Boa noite @Ironaldo-Silva,

Sim possui um problema, caso você olhar na Wiki, veras que estamos desenvolvendo um novo modelo para impressão de OS já em PDF que será disponibilizado nas próximas versões, pois está versão desorganizada vem do projeto original.

Em breve terá uma nova release com muitas novidades e correções.

**Comment by TecSecret** [comment]
Boa noite,

Isso já foi corrigido, 

Atualize o seu sistema.

Obrigado
