### ISSUE TITLE
bug na   tabela lançamentos, nao atualiza ao apagar um lançamento ou despesas

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#14]
bug na   tabela lançamentos, não atualiza ao apagar um lançamento ou despesas, e tb na tabela os na opção anexo não consegue adicionar anexo, e também estando na aba ordem de serviços querendo ir para aba financeiro não acontece nada. abraço espero ter ajudado

**Comment by TecSecret** [comment]
Bom dia @Ironaldo-Silva,

Vamos analisar o que você relatou aqui e disponibilizar um fix em breve.

Obrigado por relatar este problema.

**Comment by TecSecret** [comment]
Boa noite, 

Atualize seu sistema, isso já foi corrigido.

Abraços
