### ISSUE TITLE
problema na resolução nas estatisticas 

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#15]
ao utilizar em telas com definição menores tipo tabletes e smartphones  os gráficos não se adequam a resolução da tela e também a resolução afeta na visualizações de os, aproveitando na área do cliente o status da os deveria ser também destacada em cores  fica melhor para o cliente visualizar,  o sistema esta ficando muito bom, estou testando e reportando os erros encontrados para vocês ok espero ter ajudado abraço a todos os desenvolvedores estão de parabéns

**Comment by TecSecret** [comment]
Bom dia @Ironaldo-Silva ,

Obrigado por reportar.

Iremos analisar e disponibilizar a correção nas próximos commits.

Um grande abraço

**Comment by TecSecret** [comment]
Boa noite,

Recurso implementado.

Atualize seu sistema.

Abraços
