### ISSUE TITLE
Vendedor autonomo (Venda comissionada)

### ISSUE THREAD

**Issue by EduardoPataki** [TecSecret/TSOS#16]
Boa tarde estou um pouco perdido no endereço para adicionar um novo usuário e suas permissões. Onde está?
Quero adicionar um usuário com permissão de venda e comissionado a venda ou trabalho executado.
Qual seria o caminho para criar esta função (pasta e diretório). sou novo em PHP e quero ajudar a desenvolver esta função para OS.
Parabenizo aos desenvolvedores pelo empenho  no projeto.

**Comment by dcweb-solutions** [comment]
Olá @EduardoPataki, o que deseja saber? Os caminhos estão em application, lá você irá encontrar as pastas relacionadas ao MVC que esse framework nos disponibiliza.

**Comment by TecSecret** [comment]
Se desejar contribuir com o projeto, você pode fazer um PR das modificações, em caso de validadas as mesmas serão aplicadas no repo original.

Abraços
