### ISSUE TITLE
Novo estado (status) ENTREGUE

### ISSUE THREAD

**Issue by kalukramer** [TecSecret/TSOS#21]
Boas.
Quando existe muito fluxo de reparaçoes, por vezes já não se sabe se o finalizado foi entregue, por acaso adicionei manualmente um novo estado no ficheiro, penso que não será o mais correto, mas era óptimo ter este estado de ENTREGUE, assim sabiamos que já tinha sido entregue, não havia equipamantoes perdidos.
É uma dica válida, apesar de estar FINALIZADO, não quer dizer que o cliente o tenha levado, fica sempre a dúvida.

**Comment by TecSecret** [comment]
@kalukramer 

Obrigado pela sua sugestão, vamos analisar e possivelmente implantar nas próximas versões.

**Comment by HellBandit** [comment]
Esse campo me seria muito útil também.

**Comment by hardbrasil** [comment]
Na verdade na seleção de status do Atendimento seria interessante se possível ter: Entrada, Aguardando Análise, Aguardando Peça, aguardando Aprovação, Aguardando Retirada, Finalizado sem Reparo, Cancelada/Anulada dentre outros. E seria bacana tbm se estes status fossem vinculados a "selos" de cores.
Bacana tbm seria se ao Passar de 4 dias a Ordem este desse alerta de ordens que estiverem com campo aguardando análise ficassem em alerta.

**Comment by hardbrasil** [comment]
As ordens que completassem 22 dias sem conclusão dessem algum alerta de PERIGO - TEMPO QUALITATIVO PARA ATENDIMENTO EXPIRANDO!!!!

**Comment by P4R4G0N** [comment]
O ideal é o "Status" fosse customizável, ou seja, uma entidade para status onde quem cadastra é o administrador do sistema, cadastrando de acordo com a necessidade da empresa.
Se alguém quiser dar uma olhada em recursos muito bons para a parte de ordens de serviço veja em http://www.http://osticket.com/ http://www.http://osticket.com/download - OSTicket sistema desenvolvido em PHP
Outro sistema muito interessante para a parte de faturamento: https://invoiceplane.com/ https://github.com/InvoicePlane/InvoicePlane - InvoicePlane

**Comment by TecSecret** [comment]
Esse issue sera analisado melhor a partir de hoje.

**Comment by TecSecret** [comment]
Estado como entregue adicionado em uma atualização. Atualize o sistema

Demais solicitação constam em uma personalização que deverá ser acompanhada em projetos
