### ISSUE TITLE
Erro No input file specified.

### ISSUE THREAD

**Issue by hardbrasil** [TecSecret/TSOS#24]
Instalei a versão recente e ao abrir o dominio dá o seguinte erro: No input file specified.

O Meu servidor é: hardbrasil.pe.hu

* Alguém pode me ajudar?

**Comment by hardbrasil** [comment]
Ah ia me esquecendo parabéns pela iniciativa, não sou programador e nem designer mas tenho experiência em processos pós venda e de assistencia e posso ajudar com relatórios, documentações etc...

**Comment by TecSecret** [comment]
@hardbrasil  temos uma nova versão disponível. 

Veja se após o update o problema persiste.

Qualquer coisa nos comunique.
