### ISSUE TITLE
Tsdc.php erro

### ISSUE THREAD

**Issue by hardbrasil** [TecSecret/TSOS#25]
Ao tentar acessar apresenta o erro:

Parse error: syntax error, unexpected '[' in /home/hardbrasil/public_html/os/application/controllers/Tsdc.php on line 399
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/hardbrasil/public_html/os/system/core/CodeIgniter.php:1)

Filename: core/Common.php

Line Number: 564

A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected '['

Filename: controllers/Tsdc.php

Line Number: 399

**Comment by hardbrasil** [comment]
Por enquanto vou ter que voltar a usar o Map os mesmo ta dando erros demais perdi um tempão tentando e nada.

**Comment by TecSecret** [comment]
Olá @hardbrasil 

Exite uma nova atualização para retomada do projeto. Caso deseja pode usar a mesma.

Abraços
