### ISSUE TITLE
Opção de Faturado no Status do Relatório de OS

### ISSUE THREAD

**Issue by feralton** [TecSecret/TSOS#26]
Boa noite amigos desenvolvedores.
Existe um status para OS, o Faturado, que não aparece nas opções de status durante a geração do relatório de OS. Esse status eu utilizo para o caso da OS pronta, e o cliente ainda não veio retirar. Poderia por gentileza incluir no status de relatório da OS?

Muito obrigado.
Fernando Silva
![status](https://cloud.githubusercontent.com/assets/26724563/25361765/572153ce-2926-11e7-8a28-6fffc75371b7.jpg)

**Comment by TecSecret** [comment]
@feralton Boa tarde,

Sua Solicitação será analisada pela nossa equipe.

Um grande abraço

**Comment by TecSecret** [comment]
Recurso implantado no projeto através do projeto original.

Atualize o seus arquivos e nos reporte qualquer problema.
Abraços
