### ISSUE TITLE
Area do Cliente.

### ISSUE THREAD

**Issue by alexandresgbh** [TecSecret/TSOS#28]
Primeiramente gostaria de parabenizar os desenvolvedores o projeto esta ficando muito bom.

Estou iniciando os testes da ferramenta e me surgiu uma dúvida que não consegui encontrar.

Qual o link devo disponibilizar para o meu cliente acessar as informações de usas OS's com o código do cliente?

**Comment by Fcodapaz** [comment]
Pra acessar a área do cliente é só colocar "/conecte" depois do domínio.
ex: http://127.0.0.1/sistema/conecte 
entendeu?

**Comment by alexandresgbh** [comment]
Obrigado pelo retorno!

Entendi sim, porém não funcionou. Quando tento entrar com os dados do usuário ele não abre, veja:

http://www.alexandresg.net/teste/index.php/conecte

Usuário: alexandre.infoshop@gmail.com
Código: 1234

ou

Usuário: teste@teste.com
Código: 123456

Os 2 usuários possuem OS atribuida a eles porém não abre a página.

O acesso admin esta padrão.

Poderia me ajudar?

**Comment by TecSecret** [comment]
@alexandresgbh 

O acesso você cadastra na área do cliente no momento do cadastro do cliente.

O e-mail é o usuário e o código que você adiciona é a senha.

Abraços

**Comment by alexandresgbh** [comment]
@TecSecret obrigado pelo retorno.

Eu entendi o cadastro, o que esta acontecendo é que quando tentar acessar ele não abre. A página não responde e não muda de tela, entendeu?

O site esta ativo no link abaixo:

http://www.alexandresg.net/teste/index.php/conecte

Usuário: alexandre.infoshop@gmail.com
Código: 1234

Obrigado.

**Comment by pedro-nunes** [comment]
@alexandresgbh o seu esta com erro 404 no link http://www.alexandresg.net/teste/conecte/login?ajax=true que é responsável pelo login

**Comment by TecSecret** [comment]
Nova área do cliente disponível e funcionando. Acesse a mesma: https://dominio/mine.

Só atualizar os arquivos novamente.

Abraços

Qualquer dúvida reabra esse issues.
