### ISSUE TITLE
Erros encontrados no sistema

### ISSUE THREAD

**Issue by leocampbel** [TecSecret/TSOS#29]
Olá, usando o sistema descobri falhas.

1º na ordem de serviço, quando eu anexo algum arquivo, ele não anexa e informa a mensagem: 
"Atenção! Nenhum arquivo foi anexado."
2º na área do cliente, se ele clicar em imprimir, só sai uma tela branca.
3º Na OS na area de lançar os serviços, o botão de "+ novo serviço" não funciona e quando eu lanço o serviço no campo na OS o mesmo só fica carregando e não lança o serviço na OS, já os produtos esta ok.
4º No cadastro de serviço na campo de valores não aceita colocar virgula no valor, somente ponto
5º Na OS eu lancei 600,00 com desconto de 5,20 valor total de 594,80 nos produtos, quando eu clico em faturar o valor que aparece é 59.485,20.
6º na OS existe o botão Adicionar cliente, porem nele não existe o campo código de acesso.

Obrigado pelo ótimo sistema!

**Comment by TecSecret** [comment]
Boa noite @leocampbel,

Está sendo desenvolvida uma nova Ordem de Serviço, acredito que na próxima versão já esteja disponível.

Um grande abraço

**Comment by leocampbel** [comment]
Bom dia, @TecSecret .

Estou aguardando ansioso pela nova OS!

Obrigado pelo ótimo sistema!

**Comment by TecSecret** [comment]
@leocampbel na próxima versão do sistema será disponibilizado.

Daqui alguns dias finalizamos o desenvolvimento.

Um grande abraço

**Comment by TecSecret** [comment]
Atualize o seu sistema com a nova versão aqui disponível e veja se o problema persiste.

Voltamos com o desenvolvimento das personalizações.

Abraços
