### ISSUE TITLE
O que aconteceu, abandonaram o sistema foi?

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#30]
Pena não vejo mais ninguém interessados em terminar o sistema, estava indo tão bem

**Comment by darouca** [comment]
Olá,
Pode ser que o desenvolvimento esteja acontecendo em off. E logo apareça novidades. 
Até porquê, não teria motivos para fazer um fork do mapos e parar no meio do caminho.

**Comment by Baeth** [comment]
O clone atual do git não roda, certo?

**Comment by TecSecret** [comment]
Bom dia,

O sistema não está abandonado, apenas estamos realizando o dev sem atualizações no git, pois estamos implantando uma nova OS, ajustando muitas outras coisas, 

Em breve vai ter uma versão cheia de novidades.

**Comment by HellBandit** [comment]
@TecSecret Essas implementações irão ser aplicadas nesses mesmo projeto OpenSource do Mapos?

**Comment by TecSecret** [comment]
@HellBandit sim serão implementadas aqui e este projeto ele continuará open aberto a todos. O objetivo é manter este projeto grátis sim enquanto a TecSecret existir, pode haver alguns custos adicionais como por exemplo algo que necessite homologações que seria o caso de notas fiscais.

**Comment by HellBandit** [comment]
@TecSecret Existe uma média de tempo de quando serão lançadas as modificações? Ou ao menos uma versão Beta pra iniciar.

**Comment by feralton** [comment]
Equipe, já que estão em desenvolvimento da nfe, poderia incluir também o desenvolvimento do nfc?

**Comment by Ironaldo-Silva** [comment]
Tem alguma previsão para ser disponibilizado algum teste ?

Enviado do meu iPhone

**Comment by TecSecret** [comment]
@feralton ok, será incluído sim, mas vai demorar um pouco pra sair.

@Ironaldo-Silva temos, dentro de algumas semanas.

@HellBandit temos uma estiva de que a cada 6 meses será implementado versões denominadas releases, e outras versões menores sempre que possível para correção de bugs e outras coisas.

Um abraço

**Comment by Ironaldo-Silva** [comment]
Ainda nada do sistema, me dá uma posição ?

Atenciosamente: Ironaldo Silva

**Comment by TecSecret** [comment]
@Ironaldo-Silva 
Boa tarde,

Este projeto será reativado a partir de fevereiro de 2020. Sempre será atualizado neste mesmo repositório.

Em breve terá disponível uma nova versão.

**Comment by TecSecret** [comment]
Existe uma nova versão disponível. Atualize o seu sistema.

Acompanhe no projeto as novidades sendo implementadas.

Em caso de dúvidas entre em contato conosco.
