### ISSUE TITLE
novidades

### ISSUE THREAD

**Issue by manuelnice** [TecSecret/TSOS#33]
Boas tardes, parece nao estar a existir novidades, nem a versao demo funciona, se o projecto terminou peço autorização para poder pegar no projecto e au avançar com atualizaçoes

**Comment by TecSecret** [comment]
Boa tarde, 

Projeto será retomado a partir de fevereiro de 2020

**Comment by TecSecret** [comment]
Boa noite,

Existe uma nova versão disponível, atualize a mesma.

Caso desejar contribuir pode usar esse mesmo repositório e fazer um PR.
