### ISSUE TITLE
Boa tarde! Gostaria de saber se tem alguma previsão de liberação do novo sistema  de ordem de serviços ?

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#34]
Boa tarde! Gostaria de saber se tem alguma previsão de liberação do novo sistema  de ordem de serviços ?
Pois gostaria muito de usar em minha pequena assistência técnica em informática

**Comment by TecSecret** [comment]
Boa tarde,

Este projeto será reativado a partir de fevereiro de 2020. Sempre será atualizado neste mesmo repositório.

Em breve terá disponível uma nova versão.

**Comment by TecSecret** [comment]
Já está disponível uma nova versão.

Em caso de dúvidas entre em contato.
