### ISSUE TITLE
Tem previsão para o novo sistema 

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#35]
Boa noite estou precisando usar o sistema mais está com falhas e vi que estão preparando uma nova versão melhorada dai gostaria de saber se a previsão pois acho esse sistema muito muito interessante e bem fácil de usar, se for possível me envie alguma informação sobre o andamento do sistema se há preciso de liberação da nova versão. Grande abraço

**Comment by TecSecret** [comment]
Boa tarde,

Este projeto será reativado a partir de fevereiro de 2020. Sempre será atualizado neste mesmo repositório.

Em breve terá disponível uma nova versão.

**Comment by TecSecret** [comment]
Já possuímos uma nova versão disponível.

Qualquer dúvida entre em contato novamente
