### ISSUE TITLE
Alterar senha de administrador da erro

### ISSUE THREAD

**Issue by Simaops** [TecSecret/TSOS#36]
Após tentar alterar a senha de Minha conta de Administrador aparece a mensagem:

"Ocorreu um erro ao tentar alterar a senha!"

e não altera, como proceder?

**Comment by TecSecret** [comment]
Bom dia, tudo bem? 

Já foi corrigido no commit https://github.com/TecSecret/TSOS/commit/2d249bb3bc4bef88d7eac8d87628a818e7bb4be6

Atualize seu sistema e qualquer coisa nos comunique.

Abraços
