### ISSUE TITLE
Duvida em relação a personalização da impressão da OS

### ISSUE THREAD

**Issue by Henrique-Miranda** [TecSecret/TSOS#37]
Olá, no mapos 3.11 na hora de imprimir a OS consigo imprimir em impressoras não fiscais de 58mm.
Apenas faço um ajuste de escala para algo entre 30% a 40% e sai completamente responsivo.
Aqui no TSDC a impressão sai com a logomarca gigante, mesmo ajustando o tamanho na tag <img />
Já tentei de varias formas, pois preciso imprimir em uma impressora termica de 58mm.
Acredito que seja algo que não esteja abrindo a janela de impressão no modo responsivo.
Alguem teria alguma dica?

**Comment by TecSecret** [comment]
Boa tarde,

Tinhamos dado uma pausa no projeto, estaremos retornando o mesmo a partir de fevereiro de 2020.

**Comment by TecSecret** [comment]
Boa tarde @Henrique-Miranda 

Veja se o problema foi resolvido neste update.

Caso o problema persista nos comunique.
