### ISSUE TITLE
Tem alguma novidade sobre o sistema 

### ISSUE THREAD

**Issue by Ironaldo-Silva** [TecSecret/TSOS#38]
Olá, gostaria de saber sobre o novo sistema pois não postaram mais nada aqui, tem previsão ou já existe em outro local um sistema melhorado. Fico no aguardo grato se responder.

**Comment by TecSecret** [comment]
Boa tarde, 

Este projeto será reativado a partir de fevereiro de 2020. Sempre será atualizado neste mesmo repositório.

Em breve terá disponível uma nova versão.

**Comment by TecSecret** [comment]
Nova versão disponível.

Baixe a mesma e atualize.

Abraços
