### ISSUE TITLE
erro ao instalar sistema

### ISSUE THREAD

**Issue by mauriliolopesjunior** [TecSecret/TSOS#41]
baixado a versão v3.7 Update 2 e renomeado para index.php

Renomeio o arquivo application\config\database_new.php para database.php; ( já estava renomeado para database.php

dai acessei o host ( http://localhost/os1/install/index.php)

e da esta mensagem 
Esta página não está funcionandoRedirecionamento em excesso por localhost
Tente limpar os cookies.
ERR_TOO_MANY_REDIRECTS

XAMPP Apache + MariaDB + PHP + Perl
PHP Version 7.1.33
mysqlnd 5.0.12

segue a imagem

![TSOS](https://user-images.githubusercontent.com/41583140/84820185-39c8f980-afe7-11ea-90ed-08f4556e3765.PNG)
![tsos1](https://user-images.githubusercontent.com/41583140/84820176-346baf00-afe7-11ea-84e4-85e6f4185597.PNG)
![tsos2](https://user-images.githubusercontent.com/41583140/84820179-359cdc00-afe7-11ea-8bad-cd5b2c421634.PNG)

poderia me ajudar, obrigado.

**Comment by TecSecret** [comment]
Boa noite @mauriliolopesjunior 

Solicitamos que siga este procedimento: https://central.tecsecret.com.br/knowledgebase/8/Sistema-apresenta-erro-404-apos-instalacao-usando-apache.html

Qualqluer nova dúvida pode entrar em contato.
